"""add_pos_sync_status_to_bookings

Revision ID: 0e1ac137bdc9
Revises: c1d1a790dff0
Create Date: 2026-07-15 15:54:47.065540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1ac137bdc9'
down_revision: Union[str, Sequence[str], None] = 'c1d1a790dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pos_sync_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.alter_column('bookings', 'pos_sync_status', server_default=None)  # Bỏ server_default sau khi backfill
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'pos_sync_status')
    # ### end Alembic commands ###
