# Migration thêm trạng thái đồng bộ POS vào booking.
# Revision: 0e1ac137bdc9; revision trước: c1d1a790dff0.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1ac137bdc9'
down_revision: Union[str, Sequence[str], None] = 'c1d1a790dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Thêm cột pos_sync_status, backfill giá trị pending rồi gỡ server default tạm thời.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pos_sync_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.alter_column('bookings', 'pos_sync_status', server_default=None)  # Bỏ server_default sau khi backfill
    # ### end Alembic commands ###


# Hoàn tác migration bằng cách xóa cột pos_sync_status khỏi bảng bookings.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'pos_sync_status')
    # ### end Alembic commands ###
