"""create initial booking schema

Revision ID: dee2e56ef8bf
Revises: 
Create Date: 2026-07-15 14:19:33.476460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee2e56ef8bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_restrictions',
    sa.Column('restriction_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('restriction_id')
    )
    op.create_index('idx_active_restriction_phone', 'customer_restrictions', ['phone'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_customer_restrictions_phone'), 'customer_restrictions', ['phone'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pos_customer_code', sa.String(length=50), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('member_rank', sa.String(length=50), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('shops',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('shop_code', sa.String(length=50), nullable=False),
    sa.Column('pos_shop_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_index(op.f('ix_shops_pos_shop_code'), 'shops', ['pos_shop_code'], unique=True)
    op.create_index(op.f('ix_shops_shop_code'), 'shops', ['shop_code'], unique=True)
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('pos_course_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('course_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_shop_id'), 'courses', ['shop_id'], unique=False)
    op.create_index('uq_course_per_shop', 'courses', ['shop_id', 'pos_course_code'], unique=True)
    op.create_table('therapists',
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('pos_therapist_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.PrimaryKeyConstraint('therapist_id')
    )
    op.create_index(op.f('ix_therapists_shop_id'), 'therapists', ['shop_id'], unique=False)
    op.create_index('uq_therapist_per_shop', 'therapists', ['shop_id', 'pos_therapist_code'], unique=True)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('pos_booking_code', sa.String(length=50), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('therapist_request_type', sa.String(length=20), nullable=False),
    sa.Column('requested_therapist_id', sa.UUID(), nullable=True),
    sa.Column('requested_gender', sa.String(length=10), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['requested_therapist_id'], ['therapists.therapist_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_pos_booking_code'), 'bookings', ['pos_booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_requested_therapist_id'), 'bookings', ['requested_therapist_id'], unique=False)
    op.create_index(op.f('ix_bookings_shop_id'), 'bookings', ['shop_id'], unique=False)
    op.create_table('therapist_shifts',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.therapist_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_therapist_shifts_shop_id'), 'therapist_shifts', ['shop_id'], unique=False)
    op.create_index(op.f('ix_therapist_shifts_therapist_id'), 'therapist_shifts', ['therapist_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('person_index', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.therapist_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservations_booking_id'), 'reservations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reservations_therapist_id'), 'reservations', ['therapist_id'], unique=False)
    op.create_table('reservation_courses',
    sa.Column('reservation_course_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_role', sa.String(length=20), nullable=False),
    sa.Column('duration_snapshot', sa.Integer(), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('course_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('reservation_course_id')
    )
    op.create_index(op.f('ix_reservation_courses_course_id'), 'reservation_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_reservation_courses_reservation_id'), 'reservation_courses', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_courses_reservation_id'), table_name='reservation_courses')
    op.drop_index(op.f('ix_reservation_courses_course_id'), table_name='reservation_courses')
    op.drop_table('reservation_courses')
    op.drop_index(op.f('ix_reservations_therapist_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_booking_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_therapist_shifts_therapist_id'), table_name='therapist_shifts')
    op.drop_index(op.f('ix_therapist_shifts_shop_id'), table_name='therapist_shifts')
    op.drop_table('therapist_shifts')
    op.drop_index(op.f('ix_bookings_shop_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_requested_therapist_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pos_booking_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('uq_therapist_per_shop', table_name='therapists')
    op.drop_index(op.f('ix_therapists_shop_id'), table_name='therapists')
    op.drop_table('therapists')
    op.drop_index('uq_course_per_shop', table_name='courses')
    op.drop_index(op.f('ix_courses_shop_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_shops_shop_code'), table_name='shops')
    op.drop_index(op.f('ix_shops_pos_shop_code'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_restrictions_phone'), table_name='customer_restrictions')
    op.drop_index('idx_active_restriction_phone', table_name='customer_restrictions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('customer_restrictions')
    # ### end Alembic commands ###
