"""Danh mục dữ liệu mẫu tiếng Việt dùng bởi seed_data."""

SHOPS = [
    {"shop_code": "tokyo-sakura", "pos_shop_code": "POS-TK-001", "name": "Komorebi Quận 1", "address": "12 Nguyễn Huệ, phường Sài Gòn, Thành phố Hồ Chí Minh", "phone": "02838221201", "therapist_break_minutes": 5},
    {"shop_code": "osaka-nagomi", "pos_shop_code": "POS-OS-001", "name": "Komorebi Quận 3", "address": "86 Võ Văn Tần, phường Xuân Hòa, Thành phố Hồ Chí Minh", "phone": "02839301202", "therapist_break_minutes": 10},
    {"shop_code": "kyoto-tsukikage", "pos_shop_code": "POS-KY-001", "name": "Komorebi Thảo Điền", "address": "35 Xuân Thủy, phường An Khánh, Thành phố Hồ Chí Minh", "phone": "02837441203", "therapist_break_minutes": 15},
    {"shop_code": "yokohama-minato", "pos_shop_code": "POS-YH-001", "name": "Komorebi Phú Nhuận", "address": "128 Phan Xích Long, phường Cầu Kiệu, Thành phố Hồ Chí Minh", "phone": "02835171204", "therapist_break_minutes": 5},
    {"shop_code": "sapporo-yuki", "pos_shop_code": "POS-SP-001", "name": "Komorebi Bình Thạnh", "address": "220 Nguyễn Gia Trí, phường Thạnh Mỹ Tây, Thành phố Hồ Chí Minh", "phone": "02838991205", "therapist_break_minutes": 10},
    {"shop_code": "fukuoka-hakata", "pos_shop_code": "POS-FK-001", "name": "Komorebi Quận 7", "address": "42 Nguyễn Thị Thập, phường Tân Hưng, Thành phố Hồ Chí Minh", "phone": "02837751206", "therapist_break_minutes": 15},
    {"shop_code": "nagoya-aoi", "pos_shop_code": "POS-NG-001", "name": "Komorebi Gò Vấp", "address": "18 Quang Trung, phường Hạnh Thông, Thành phố Hồ Chí Minh", "phone": "02838951207", "therapist_break_minutes": 5},
    {"shop_code": "kobe-rokkou", "pos_shop_code": "POS-KB-001", "name": "Komorebi Tân Bình", "address": "105 Cộng Hòa, phường Bảy Hiền, Thành phố Hồ Chí Minh", "phone": "02838111208", "therapist_break_minutes": 10},
    {"shop_code": "sendai-aoba", "pos_shop_code": "POS-SD-001", "name": "Komorebi Hoàn Kiếm", "address": "24 Tràng Tiền, phường Hoàn Kiếm, Hà Nội", "phone": "02438261209", "therapist_break_minutes": 15},
    {"shop_code": "hiroshima-momiji", "pos_shop_code": "POS-HS-001", "name": "Komorebi Ba Đình", "address": "68 Kim Mã, phường Giảng Võ, Hà Nội", "phone": "02437261210", "therapist_break_minutes": 5},
    {"shop_code": "kanazawa-kaga", "pos_shop_code": "POS-KZ-001", "name": "Komorebi Cầu Giấy", "address": "90 Trần Thái Tông, phường Cầu Giấy, Hà Nội", "phone": "02437681211", "therapist_break_minutes": 10},
    {"shop_code": "naha-chura", "pos_shop_code": "POS-NH-001", "name": "Komorebi Tây Hồ", "address": "15 Xuân Diệu, phường Tây Hồ, Hà Nội", "phone": "02437181212", "therapist_break_minutes": 15},
    {"shop_code": "chiba-narita", "pos_shop_code": "POS-CB-001", "name": "Komorebi Hải Châu", "address": "36 Bạch Đằng, phường Hải Châu, Đà Nẵng", "phone": "02363821213", "therapist_break_minutes": 5},
    {"shop_code": "saitama-omiya", "pos_shop_code": "POS-ST-001", "name": "Komorebi Sơn Trà", "address": "72 Võ Nguyên Giáp, phường An Hải, Đà Nẵng", "phone": "02363941214", "therapist_break_minutes": 10},
    {"shop_code": "niigata-shinano", "pos_shop_code": "POS-NI-001", "name": "Komorebi Nha Trang", "address": "20 Trần Phú, phường Nha Trang, Khánh Hòa", "phone": "02583521215", "therapist_break_minutes": 15},
    {"shop_code": "shizuoka-fuji", "pos_shop_code": "POS-SZ-001", "name": "Komorebi Đà Lạt", "address": "11 Trần Quốc Toản, phường Xuân Hương, Lâm Đồng", "phone": "02633821216", "therapist_break_minutes": 5},
    {"shop_code": "okayama-koraku", "pos_shop_code": "POS-OY-001", "name": "Komorebi Huế", "address": "28 Lê Lợi, phường Thuận Hóa, Thành phố Huế", "phone": "02343821217", "therapist_break_minutes": 10},
    {"shop_code": "kagoshima-sakurajima", "pos_shop_code": "POS-KG-001", "name": "Komorebi Hội An", "address": "52 Trần Phú, phường Hội An, Đà Nẵng", "phone": "02353861218", "therapist_break_minutes": 15},
    {"shop_code": "kumamoto-aso", "pos_shop_code": "POS-KM-001", "name": "Komorebi Cần Thơ", "address": "40 Hai Bà Trưng, phường Ninh Kiều, Cần Thơ", "phone": "02923821219", "therapist_break_minutes": 5},
    {"shop_code": "matsuyama-dogo", "pos_shop_code": "POS-MY-001", "name": "Komorebi Hạ Long", "address": "88 Hạ Long, phường Bãi Cháy, Quảng Ninh", "phone": "02033821220", "therapist_break_minutes": 10},
]

COURSE_TEMPLATES = {
    "tokyo-sakura": [
        ("zen-balance", "Massage cân bằng Zen", 60, "450000", "main"),
        ("zen-balance-plus", "Massage cân bằng Zen chuyên sâu", 90, "620000", "main"),
        ("deep-reset", "Massage phục hồi cơ sâu", 75, "690000", "main"),
        ("aroma-unwind", "Massage tinh dầu thư giãn", 90, "790000", "main"),
        ("shiatsu-flow", "Massage shiatsu cân bằng khí huyết", 60, "560000", "main"),
        ("sleep-therapy", "Liệu trình thư giãn hỗ trợ giấc ngủ", 75, "710000", "main"),
        ("mom-to-be-care", "Massage thư giãn mẹ bầu", 60, "640000", "main"),
        ("matcha-foot-ritual", "Nghi thức ngâm chân matcha", 30, "180000", "addon"),
        ("scalp-clarity", "Chăm sóc da đầu thanh lọc", 30, "250000", "addon"),
        ("warm-herb-compress", "Chườm thảo mộc ấm", 30, "220000", "addon"),
        ("hand-softening", "Dưỡng tay mềm mịn", 20, "160000", "addon"),
        ("tea-eye-mask", "Ủ mắt trà thảo mộc", 20, "150000", "addon"),
        ("back-hot-pack", "Đắp lưng thảo mộc nóng", 20, "175000", "addon"),
    ],
    "osaka-nagomi": [
        ("nagomi-flow", "Massage thư giãn Nagomi", 60, "470000", "main"),
        ("thai-stretch-journey", "Massage kéo giãn trị liệu", 90, "730000", "main"),
        ("pressure-point-revive", "Massage bấm huyệt phục hồi", 75, "680000", "main"),
        ("oil-serenity", "Massage tinh dầu an yên", 90, "810000", "main"),
        ("office-reset", "Massage phục hồi dân văn phòng", 60, "540000", "main"),
        ("lymph-care", "Massage dẫn lưu thư giãn", 75, "700000", "main"),
        ("post-workout-ease", "Massage thả lỏng sau vận động", 90, "835000", "main"),
        ("yuzu-foot-soak", "Ngâm chân yuzu", 30, "190000", "addon"),
        ("shoulder-release", "Giải tỏa cổ vai gáy", 30, "230000", "addon"),
        ("steam-reset", "Xông hơi thư giãn", 30, "210000", "addon"),
        ("arm-relief", "Massage tay giảm mỏi", 20, "155000", "addon"),
        ("mini-facial", "Chăm sóc da mặt cơ bản", 30, "240000", "addon"),
        ("herbal-belly-wrap", "Ủ bụng thảo mộc", 20, "165000", "addon"),
    ],
    "kyoto-tsukikage": [
        ("moonlight-therapy", "Massage trị liệu Ánh Trăng", 60, "490000", "main"),
        ("kyoto-aroma-ritual", "Nghi thức tinh dầu Kyoto", 90, "820000", "main"),
        ("meridian-renewal", "Massage khai mở kinh lạc", 75, "710000", "main"),
        ("hot-stone-harmony", "Massage đá nóng hài hòa", 90, "890000", "main"),
        ("detox-bamboo", "Massage tre thanh lọc cơ thể", 75, "760000", "main"),
        ("neck-jaw-release", "Massage giải tỏa cổ vai hàm", 60, "580000", "main"),
        ("silk-skin-ritual", "Nghi thức dưỡng da lụa mềm", 90, "845000", "main"),
        ("rice-bran-footbath", "Ngâm chân cám gạo", 30, "200000", "addon"),
        ("head-spa-ritual", "Nghi thức thư giãn da đầu", 30, "260000", "addon"),
        ("herbal-eye-relief", "Thư giãn mắt thảo mộc", 20, "170000", "addon"),
        ("face-gua-sha", "Gua sha thư giãn gương mặt", 20, "180000", "addon"),
        ("shoulder-hot-stone", "Đá nóng vùng vai gáy", 20, "190000", "addon"),
        ("hand-reflexology", "Bấm huyệt bàn tay", 20, "160000", "addon"),
    ],
    "yokohama-minato": [
        ("harbor-recovery", "Massage phục hồi năng lượng", 60, "460000", "main"),
        ("marine-breeze-aroma", "Massage tinh dầu gió biển", 90, "800000", "main"),
        ("athlete-reset", "Massage phục hồi vận động", 75, "720000", "main"),
        ("stone-wave-therapy", "Massage đá nóng tuần hoàn", 90, "870000", "main"),
        ("lower-back-care", "Massage thắt lưng chuyên sâu", 60, "550000", "main"),
        ("jetlag-reset", "Liệu trình phục hồi nhịp sinh học", 75, "705000", "main"),
        ("deep-tissue-harbor", "Massage mô sâu vùng lưng chân", 90, "840000", "main"),
        ("sea-salt-foot-soak", "Ngâm chân muối khoáng", 30, "185000", "addon"),
        ("back-release", "Thư giãn lưng vai chuyên sâu", 30, "235000", "addon"),
        ("cooling-face-mask", "Mặt nạ làm dịu da", 20, "190000", "addon"),
        ("calf-recovery", "Massage bắp chân phục hồi", 20, "165000", "addon"),
        ("aroma-chest-compress", "Chườm ngực tinh dầu", 20, "175000", "addon"),
        ("hydration-boost", "Dưỡng ẩm nhanh cho da", 20, "185000", "addon"),
    ],
    "sapporo-yuki": [
        ("snow-calm", "Massage thư giãn Tuyết", 60, "455000", "main"),
        ("winter-warm-oil", "Massage tinh dầu giữ ấm", 90, "795000", "main"),
        ("muscle-melt", "Massage tan cơ mỏi", 75, "700000", "main"),
        ("nordic-stone-care", "Massage đá nóng phục hồi", 90, "885000", "main"),
        ("cold-day-recovery", "Liệu trình phục hồi ngày lạnh", 60, "545000", "main"),
        ("deep-sleep-warmth", "Massage giữ ấm hỗ trợ ngủ sâu", 75, "715000", "main"),
        ("joint-comfort-therapy", "Massage thư giãn khớp cơ", 90, "830000", "main"),
        ("ginger-footbath", "Ngâm chân gừng ấm", 30, "195000", "addon"),
        ("scalp-warm-oil", "Ủ đầu tinh dầu ấm", 30, "255000", "addon"),
        ("herbal-sauna", "Xông thảo dược giữ ấm", 30, "205000", "addon"),
        ("warm-neck-wrap", "Ủ ấm cổ vai", 20, "170000", "addon"),
        ("foot-reflex-warm", "Bấm huyệt chân giữ ấm", 20, "180000", "addon"),
        ("cocoa-body-mask", "Ủ cơ thể cacao ấm", 30, "225000", "addon"),
    ],
}

SURNAMES = ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương", "Lý", "Đinh", "Mai", "Trịnh", "Đoàn", "Lâm", "Tạ", "Cao", "Chu", "Quách", "La", "Tôn", "Thái", "Hà", "Kiều"]
FEMALE_NAMES = ["Ngọc Anh", "Minh Anh", "Thùy Linh", "Khánh Linh", "Phương Thảo", "Thu Trang", "Hồng Nhung", "Bảo Ngọc", "Thanh Huyền", "Kim Oanh", "Hải Yến", "Mai Chi", "Diệu Linh", "Quỳnh Anh", "Tú Anh", "Ánh Dương", "Nhã Phương", "Uyên Nhi", "Thảo Vy", "Hoài An", "Trúc Linh", "Mỹ Duyên", "Thiên Hương", "Thanh Mai"]
MALE_NAMES = ["Minh Quân", "Đức Anh", "Quang Huy", "Hoàng Nam", "Tuấn Anh", "Hữu Phúc", "Gia Bảo", "Thanh Tùng", "Đình Khôi", "Nhật Minh", "Xuân Trường", "Tiến Dũng", "Anh Tuấn", "Mạnh Hùng", "Trọng Nghĩa", "Bảo Long", "Thành Đạt", "Quốc Bảo", "Khắc Duy", "Hải Đăng", "Thiện Nhân", "Trung Kiên", "Minh Khang", "Đăng Khoa"]

RESTRICTIONS = [
    {"phone": "0320000001", "reason": "Khách nhiều lần không đến và không báo trước", "is_active": True},
    {"phone": "0760000002", "reason": "Có hành vi gây ảnh hưởng đến nhân viên", "is_active": True},
    {"phone": "0900000003", "reason": "Vấn đề thanh toán chưa được giải quyết", "is_active": True},
    {"phone": "0320000004", "reason": "Chưa hoàn tất xác minh thông tin khách hàng", "is_active": True},
    {"phone": "0760000005", "reason": "Đã gỡ hạn chế sau khi trao đổi với cửa hàng", "is_active": False},
    {"phone": "0900000006", "reason": "Chưa xác nhận đồng ý với quy định đặt lịch", "is_active": True},
]
