"""Danh mục dữ liệu mẫu tiếng Việt dùng bởi seed_data."""

SHOPS = [
    {"shop_code": "tokyo-sakura", "pos_shop_code": "POS-TK-001", "name": "Komorebi Quận 1", "address": "12 Nguyễn Huệ, phường Sài Gòn, Thành phố Hồ Chí Minh", "phone": "02838221201", "therapist_break_minutes": 5},
    {"shop_code": "osaka-nagomi", "pos_shop_code": "POS-OS-001", "name": "Komorebi Quận 3", "address": "86 Võ Văn Tần, phường Xuân Hòa, Thành phố Hồ Chí Minh", "phone": "02839301202", "therapist_break_minutes": 10},
    {"shop_code": "kyoto-tsukikage", "pos_shop_code": "POS-KY-001", "name": "Komorebi Thảo Điền", "address": "35 Xuân Thủy, phường An Khánh, Thành phố Hồ Chí Minh", "phone": "02837441203", "therapist_break_minutes": 15},
    {"shop_code": "yokohama-minato", "pos_shop_code": "POS-YH-001", "name": "Komorebi Phú Nhuận", "address": "128 Phan Xích Long, phường Cầu Kiệu, Thành phố Hồ Chí Minh", "phone": "02835171204", "therapist_break_minutes": 5},
    {"shop_code": "sapporo-yuki", "pos_shop_code": "POS-SP-001", "name": "Komorebi Bình Thạnh", "address": "220 Nguyễn Gia Trí, phường Thạnh Mỹ Tây, Thành phố Hồ Chí Minh", "phone": "02838991205", "therapist_break_minutes": 10},
    {"shop_code": "fukuoka-hakata", "pos_shop_code": "POS-FK-001", "name": "Komorebi Quận 7", "address": "42 Nguyễn Thị Thập, phường Tân Hưng, Thành phố Hồ Chí Minh", "phone": "02837751206", "therapist_break_minutes": 15},
    {"shop_code": "nagoya-aoi", "pos_shop_code": "POS-NG-001", "name": "Komorebi Gò Vấp", "address": "18 Quang Trung, phường Hạnh Thông, Thành phố Hồ Chí Minh", "phone": "02838951207", "therapist_break_minutes": 5},
    {"shop_code": "kobe-rokkou", "pos_shop_code": "POS-KB-001", "name": "Komorebi Tân Bình", "address": "105 Cộng Hòa, phường Bảy Hiền, Thành phố Hồ Chí Minh", "phone": "02838111208", "therapist_break_minutes": 10},
    {"shop_code": "sendai-aoba", "pos_shop_code": "POS-SD-001", "name": "Komorebi Hoàn Kiếm", "address": "24 Tràng Tiền, phường Hoàn Kiếm, Hà Nội", "phone": "02438261209", "therapist_break_minutes": 15},
    {"shop_code": "hiroshima-momiji", "pos_shop_code": "POS-HS-001", "name": "Komorebi Ba Đình", "address": "68 Kim Mã, phường Giảng Võ, Hà Nội", "phone": "02437261210", "therapist_break_minutes": 5},
    {"shop_code": "kanazawa-kaga", "pos_shop_code": "POS-KZ-001", "name": "Komorebi Cầu Giấy", "address": "90 Trần Thái Tông, phường Cầu Giấy, Hà Nội", "phone": "02437681211", "therapist_break_minutes": 10},
    {"shop_code": "naha-chura", "pos_shop_code": "POS-NH-001", "name": "Komorebi Tây Hồ", "address": "15 Xuân Diệu, phường Tây Hồ, Hà Nội", "phone": "02437181212", "therapist_break_minutes": 15},
    {"shop_code": "chiba-narita", "pos_shop_code": "POS-CB-001", "name": "Komorebi Hải Châu", "address": "36 Bạch Đằng, phường Hải Châu, Đà Nẵng", "phone": "02363821213", "therapist_break_minutes": 5},
    {"shop_code": "saitama-omiya", "pos_shop_code": "POS-ST-001", "name": "Komorebi Sơn Trà", "address": "72 Võ Nguyên Giáp, phường An Hải, Đà Nẵng", "phone": "02363941214", "therapist_break_minutes": 10},
    {"shop_code": "niigata-shinano", "pos_shop_code": "POS-NI-001", "name": "Komorebi Nha Trang", "address": "20 Trần Phú, phường Nha Trang, Khánh Hòa", "phone": "02583521215", "therapist_break_minutes": 15},
    {"shop_code": "shizuoka-fuji", "pos_shop_code": "POS-SZ-001", "name": "Komorebi Đà Lạt", "address": "11 Trần Quốc Toản, phường Xuân Hương, Lâm Đồng", "phone": "02633821216", "therapist_break_minutes": 5},
    {"shop_code": "okayama-koraku", "pos_shop_code": "POS-OY-001", "name": "Komorebi Huế", "address": "28 Lê Lợi, phường Thuận Hóa, Thành phố Huế", "phone": "02343821217", "therapist_break_minutes": 10},
    {"shop_code": "kagoshima-sakurajima", "pos_shop_code": "POS-KG-001", "name": "Komorebi Hội An", "address": "52 Trần Phú, phường Hội An, Đà Nẵng", "phone": "02353861218", "therapist_break_minutes": 15},
    {"shop_code": "kumamoto-aso", "pos_shop_code": "POS-KM-001", "name": "Komorebi Cần Thơ", "address": "40 Hai Bà Trưng, phường Ninh Kiều, Cần Thơ", "phone": "02923821219", "therapist_break_minutes": 5},
    {"shop_code": "matsuyama-dogo", "pos_shop_code": "POS-MY-001", "name": "Komorebi Hạ Long", "address": "88 Hạ Long, phường Bãi Cháy, Quảng Ninh", "phone": "02033821220", "therapist_break_minutes": 10},
]

COURSE_TEMPLATES = {
    "tokyo-sakura": [
        ("zen-balance", "Massage cân bằng Zen", 60, "450000", "main"),
        ("zen-balance-plus", "Massage cân bằng Zen chuyên sâu", 90, "620000", "main"),
        ("deep-reset", "Massage phục hồi cơ sâu", 75, "690000", "main"),
        ("aroma-unwind", "Massage tinh dầu thư giãn", 90, "790000", "main"),
        ("shiatsu-flow", "Massage shiatsu cân bằng khí huyết", 60, "560000", "main"),
        ("sleep-therapy", "Liệu trình thư giãn hỗ trợ giấc ngủ", 75, "710000", "main"),
        ("mom-to-be-care", "Massage thư giãn mẹ bầu", 60, "640000", "main"),
        ("matcha-foot-ritual", "Nghi thức ngâm chân matcha", 30, "180000", "addon"),
        ("scalp-clarity", "Chăm sóc da đầu thanh lọc", 30, "250000", "addon"),
        ("warm-herb-compress", "Chườm thảo mộc ấm", 30, "220000", "addon"),
        ("hand-softening", "Dưỡng tay mềm mịn", 30, "160000", "addon"),
        ("tea-eye-mask", "Ủ mắt trà thảo mộc", 30, "150000", "addon"),
        ("back-hot-pack", "Đắp lưng thảo mộc nóng", 30, "175000", "addon"),
    ],
    "osaka-nagomi": [
        ("nagomi-flow", "Massage thư giãn Nagomi", 60, "470000", "main"),
        ("thai-stretch-journey", "Massage kéo giãn trị liệu", 90, "730000", "main"),
        ("pressure-point-revive", "Massage bấm huyệt phục hồi", 75, "680000", "main"),
        ("oil-serenity", "Massage tinh dầu an yên", 90, "810000", "main"),
        ("office-reset", "Massage phục hồi dân văn phòng", 60, "540000", "main"),
        ("lymph-care", "Massage dẫn lưu thư giãn", 75, "700000", "main"),
        ("post-workout-ease", "Massage thả lỏng sau vận động", 90, "835000", "main"),
        ("yuzu-foot-soak", "Ngâm chân yuzu", 30, "190000", "addon"),
        ("shoulder-release", "Giải tỏa cổ vai gáy", 30, "230000", "addon"),
        ("steam-reset", "Xông hơi thư giãn", 30, "210000", "addon"),
        ("arm-relief", "Massage tay giảm mỏi", 30, "155000", "addon"),
        ("mini-facial", "Chăm sóc da mặt cơ bản", 30, "240000", "addon"),
        ("herbal-belly-wrap", "Ủ bụng thảo mộc", 30, "165000", "addon"),
    ],
    "kyoto-tsukikage": [
        ("moonlight-therapy", "Massage trị liệu Ánh Trăng", 60, "490000", "main"),
        ("kyoto-aroma-ritual", "Nghi thức tinh dầu Kyoto", 90, "820000", "main"),
        ("meridian-renewal", "Massage khai mở kinh lạc", 75, "710000", "main"),
        ("hot-stone-harmony", "Massage đá nóng hài hòa", 90, "890000", "main"),
        ("detox-bamboo", "Massage tre thanh lọc cơ thể", 75, "760000", "main"),
        ("neck-jaw-release", "Massage giải tỏa cổ vai hàm", 60, "580000", "main"),
        ("silk-skin-ritual", "Nghi thức dưỡng da lụa mềm", 90, "845000", "main"),
        ("rice-bran-footbath", "Ngâm chân cám gạo", 30, "200000", "addon"),
        ("head-spa-ritual", "Nghi thức thư giãn da đầu", 30, "260000", "addon"),
        ("herbal-eye-relief", "Thư giãn mắt thảo mộc", 30, "170000", "addon"),
        ("face-gua-sha", "Gua sha thư giãn gương mặt", 30, "180000", "addon"),
        ("shoulder-hot-stone", "Đá nóng vùng vai gáy", 30, "190000", "addon"),
        ("hand-reflexology", "Bấm huyệt bàn tay", 30, "160000", "addon"),
    ],
    "yokohama-minato": [
        ("harbor-recovery", "Massage phục hồi năng lượng", 60, "460000", "main"),
        ("marine-breeze-aroma", "Massage tinh dầu gió biển", 90, "800000", "main"),
        ("athlete-reset", "Massage phục hồi vận động", 75, "720000", "main"),
        ("stone-wave-therapy", "Massage đá nóng tuần hoàn", 90, "870000", "main"),
        ("lower-back-care", "Massage thắt lưng chuyên sâu", 60, "550000", "main"),
        ("jetlag-reset", "Liệu trình phục hồi nhịp sinh học", 75, "705000", "main"),
        ("deep-tissue-harbor", "Massage mô sâu vùng lưng chân", 90, "840000", "main"),
        ("sea-salt-foot-soak", "Ngâm chân muối khoáng", 30, "185000", "addon"),
        ("back-release", "Thư giãn lưng vai chuyên sâu", 30, "235000", "addon"),
        ("cooling-face-mask", "Mặt nạ làm dịu da", 30, "190000", "addon"),
        ("calf-recovery", "Massage bắp chân phục hồi", 30, "165000", "addon"),
        ("aroma-chest-compress", "Chườm ngực tinh dầu", 30, "175000", "addon"),
        ("hydration-boost", "Dưỡng ẩm nhanh cho da", 30, "185000", "addon"),
    ],
    "sapporo-yuki": [
        ("snow-calm", "Massage thư giãn Tuyết", 60, "455000", "main"),
        ("winter-warm-oil", "Massage tinh dầu giữ ấm", 90, "795000", "main"),
        ("muscle-melt", "Massage tan cơ mỏi", 75, "700000", "main"),
        ("nordic-stone-care", "Massage đá nóng phục hồi", 90, "885000", "main"),
        ("cold-day-recovery", "Liệu trình phục hồi ngày lạnh", 60, "545000", "main"),
        ("deep-sleep-warmth", "Massage giữ ấm hỗ trợ ngủ sâu", 75, "715000", "main"),
        ("joint-comfort-therapy", "Massage thư giãn khớp cơ", 90, "830000", "main"),
        ("ginger-footbath", "Ngâm chân gừng ấm", 30, "195000", "addon"),
        ("scalp-warm-oil", "Ủ đầu tinh dầu ấm", 30, "255000", "addon"),
        ("herbal-sauna", "Xông thảo dược giữ ấm", 30, "205000", "addon"),
        ("warm-neck-wrap", "Ủ ấm cổ vai", 30, "170000", "addon"),
        ("foot-reflex-warm", "Bấm huyệt chân giữ ấm", 30, "180000", "addon"),
        ("cocoa-body-mask", "Ủ cơ thể cacao ấm", 30, "225000", "addon"),
    ],
}

# Bổ sung catalog cho 5 shop đang dùng trong seed local để chatbot/admin có nhiều
# lựa chọn main course và add-on hơn khi test duration, combo dịch vụ và slot.
ADDITIONAL_COURSE_TEMPLATES = {
    "tokyo-sakura": [
        ("zen-quick-reset-45", "Massage thư giãn Zen nhanh", 45, "390000", "main"),
        ("tea-aroma-balance-60", "Massage hương trà cân bằng", 60, "575000", "main"),
        ("deep-zen-release-75", "Massage giải phóng cơ sâu Zen", 75, "735000", "main"),
        ("stone-sleep-ritual-90", "Liệu trình đá nóng hỗ trợ ngủ sâu", 90, "865000", "main"),
        ("premium-zen-retreat-120", "Trải nghiệm Zen retreat toàn thân", 120, "1190000", "main"),
        ("mini-scalp-refresh-15", "Thư giãn da đầu nhanh", 15, "120000", "addon"),
        ("warm-eye-relief-20", "Ủ mắt thảo mộc thư giãn", 20, "145000", "addon"),
        ("matcha-hand-care-20", "Dưỡng tay matcha", 20, "150000", "addon"),
        ("neck-hot-compress-30", "Chườm nóng cổ vai", 30, "195000", "addon"),
        ("foot-aroma-finish-45", "Ngâm chân tinh dầu kéo dài", 45, "260000", "addon"),
    ],
    "osaka-nagomi": [
        ("nagomi-quick-relax-45", "Massage Nagomi thư giãn nhanh", 45, "395000", "main"),
        ("shoulder-back-reset-60", "Massage cổ vai lưng phục hồi", 60, "565000", "main"),
        ("muscle-care-nagomi-75", "Massage chăm sóc cơ Nagomi", 75, "725000", "main"),
        ("aroma-deep-calm-90", "Massage tinh dầu thư giãn sâu", 90, "850000", "main"),
        ("full-body-retreat-120", "Liệu trình phục hồi toàn thân", 120, "1180000", "main"),
        ("quick-hand-relief-15", "Bấm huyệt tay nhanh", 15, "115000", "addon"),
        ("yuzu-eye-mask-20", "Ủ mắt yuzu thư giãn", 20, "145000", "addon"),
        ("warm-foot-compress-20", "Chườm ấm bàn chân", 20, "155000", "addon"),
        ("neck-therapy-plus-30", "Trị liệu cổ vai chuyên sâu", 30, "240000", "addon"),
        ("steam-herb-plus-45", "Xông hơi thảo mộc kéo dài", 45, "290000", "addon"),
    ],
    "kyoto-tsukikage": [
        ("kyoto-calm-45", "Massage Kyoto thư giãn nhanh", 45, "405000", "main"),
        ("meridian-soft-flow-60", "Massage kinh lạc thư giãn", 60, "585000", "main"),
        ("bamboo-balance-75", "Massage tre cân bằng cơ thể", 75, "755000", "main"),
        ("moon-aroma-deep-90", "Nghi thức tinh dầu Ánh Trăng", 90, "875000", "main"),
        ("tsukikage-signature-120", "Liệu trình Tsukikage signature", 120, "1220000", "main"),
        ("herbal-eye-mini-15", "Ủ mắt thảo mộc nhanh", 15, "120000", "addon"),
        ("rice-foot-mini-20", "Ngâm chân cám gạo ngắn", 20, "155000", "addon"),
        ("face-gua-sha-mini-20", "Gua sha mặt nhẹ", 20, "165000", "addon"),
        ("shoulder-stone-plus-30", "Đá nóng cổ vai chuyên sâu", 30, "215000", "addon"),
        ("head-ritual-plus-45", "Nghi thức thư giãn da đầu kéo dài", 45, "315000", "addon"),
    ],
    "yokohama-minato": [
        ("harbor-quick-reset-45", "Massage phục hồi nhanh Harbor", 45, "390000", "main"),
        ("marine-relax-60", "Massage thư giãn gió biển", 60, "555000", "main"),
        ("leg-back-recovery-75", "Massage phục hồi lưng chân", 75, "730000", "main"),
        ("stone-wave-premium-90", "Massage đá nóng sóng biển", 90, "875000", "main"),
        ("minato-wellness-120", "Liệu trình Minato wellness", 120, "1210000", "main"),
        ("calf-mini-release-15", "Thả lỏng bắp chân nhanh", 15, "110000", "addon"),
        ("salt-foot-mini-20", "Ngâm chân muối khoáng ngắn", 20, "150000", "addon"),
        ("cool-face-mini-20", "Làm dịu da mặt nhanh", 20, "160000", "addon"),
        ("back-aroma-compress-30", "Chườm lưng tinh dầu", 30, "210000", "addon"),
        ("hydration-body-care-45", "Dưỡng ẩm cơ thể chuyên sâu", 45, "320000", "addon"),
    ],
    "sapporo-yuki": [
        ("snow-quick-warm-45", "Massage làm ấm nhanh", 45, "400000", "main"),
        ("warm-joint-care-60", "Massage chăm sóc khớp cơ ấm", 60, "570000", "main"),
        ("winter-muscle-reset-75", "Massage phục hồi cơ ngày lạnh", 75, "740000", "main"),
        ("cocoa-warm-ritual-90", "Liệu trình cacao giữ ấm", 90, "880000", "main"),
        ("sapporo-snow-retreat-120", "Trải nghiệm Snow retreat toàn thân", 120, "1230000", "main"),
        ("ginger-foot-mini-15", "Ngâm chân gừng nhanh", 15, "120000", "addon"),
        ("warm-scalp-mini-20", "Ủ đầu tinh dầu ngắn", 20, "165000", "addon"),
        ("neck-warm-mini-20", "Ủ ấm cổ vai nhanh", 20, "150000", "addon"),
        ("foot-reflex-plus-30", "Bấm huyệt chân chuyên sâu", 30, "220000", "addon"),
        ("herbal-sauna-plus-45", "Xông thảo dược giữ ấm kéo dài", 45, "300000", "addon"),
    ],
}

for shop_code, course_items in ADDITIONAL_COURSE_TEMPLATES.items():
    COURSE_TEMPLATES[shop_code].extend(course_items)

SURNAMES = ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương", "Lý", "Đinh", "Mai", "Trịnh", "Đoàn", "Lâm", "Tạ", "Cao", "Chu", "Quách", "La", "Tôn", "Thái", "Hà", "Kiều"]
FEMALE_NAMES = ["Ngọc Anh", "Minh Anh", "Thùy Linh", "Khánh Linh", "Phương Thảo", "Thu Trang", "Hồng Nhung", "Bảo Ngọc", "Thanh Huyền", "Kim Oanh", "Hải Yến", "Mai Chi", "Diệu Linh", "Quỳnh Anh", "Tú Anh", "Ánh Dương", "Nhã Phương", "Uyên Nhi", "Thảo Vy", "Hoài An", "Trúc Linh", "Mỹ Duyên", "Thiên Hương", "Thanh Mai"]
MALE_NAMES = ["Minh Quân", "Đức Anh", "Quang Huy", "Hoàng Nam", "Tuấn Anh", "Hữu Phúc", "Gia Bảo", "Thanh Tùng", "Đình Khôi", "Nhật Minh", "Xuân Trường", "Tiến Dũng", "Anh Tuấn", "Mạnh Hùng", "Trọng Nghĩa", "Bảo Long", "Thành Đạt", "Quốc Bảo", "Khắc Duy", "Hải Đăng", "Thiện Nhân", "Trung Kiên", "Minh Khang", "Đăng Khoa"]

RESTRICTIONS = [
    {"phone": "0320000001", "reason": "Khách nhiều lần không đến và không báo trước", "is_active": True},
    {"phone": "0760000002", "reason": "Có hành vi gây ảnh hưởng đến nhân viên", "is_active": True},
    {"phone": "0900000003", "reason": "Vấn đề thanh toán chưa được giải quyết", "is_active": True},
    {"phone": "0320000004", "reason": "Chưa hoàn tất xác minh thông tin khách hàng", "is_active": True},
    {"phone": "0760000005", "reason": "Đã gỡ hạn chế sau khi trao đổi với cửa hàng", "is_active": False},
    {"phone": "0900000006", "reason": "Chưa xác nhận đồng ý với quy định đặt lịch", "is_active": True},
]
